# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Authenticate
      run: dotnet nuget add source --username CriusNyx --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/CriusNyxUtil/index.json"
    - name: Publish
      run: (cd core && dotnet pack --configuration Release) && dotnet nuget push "core/bin/Release/CriusNyxUtil.1.0.0.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
