# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - uses: actions/upload-artifact@v4
      with: 
        name: core
        path: ./core/bin
    - uses: actions/upload-artifact@v4
      with:
        name: tests
        path: ./tests/bin
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - uses: actions/download-artifact@v4
      with:
        name: core
        path: ./core/bin
    - uses: actions/download-artifact@v4
      with:
        name: tests
        path: ./tests/bin
    - name: Test
      run: dotnet test --no-build --verbosity normal
  version:
    name: Update Version Info
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Git
      run: |
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
    - name: Get project version from .csproj
      shell: bash
      run: |
        # Get a project version from the *.csproj file
        cat ./core/core.csproj
        VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" ./core/core.csproj)
        echo "Test"
        echo "Project version in $VERSION"
        # Save the result into the variable VERSION
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    - name: Get latest tag
      id: tag
      run: |
        # Get the latest release version according to the latest version tag from the repository
        git fetch --tags
        LATEST_TAG=$(git tag -l "v*" --sort=-v:refname | head -n 1)
        echo "Latest tag: $LATEST_TAG"
        # Save the result into the variable LATEST_TAG
        echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
    - name: Compare Strings
      id: compare_versions
      run: |
        # Find the max version by comparing VERSION and LATEST_TAG and save the result into the variable GREATER_VERSION
        GREATER_VERSION=$(printf "%s\n%s" "$VERSION" "${LATEST_TAG#v}" | sort -V | tail -n 1)
        if [[ "$VERSION" == "$GREATER_VERSION" && "$VERSION" != "${LATEST_TAG#v}" ]]; then
          # If the version in the project configuration file is higher than the tag version, then the check is passed.
          echo "The new release version is ${LATEST_TAG#v}"
          echo "is_valid=true" >> $GITHUB_OUTPUT
        else
          # Otherwise it is signaled about the error
          echo "The project version is not incremented"
          echo "is_valid=false" >> $GITHUB_OUTPUT
        fi
    - name: Increment version
      run: |
        NEXT_VERSION=$(echo ${GREATER_VERSION} | awk -F. -v OFS=. '{$NF += 1 ; print}')
        echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_OUTPUT
    - name: Create and push tag
      run: |
        NEW_TAG="v$NEXT_VERSION"
        git tag $NEW_TAG
        echo "Tag created: $NEW_TAG"
        git push origin $NEW_TAG 
